// Gallery registry: one entry per @onda/components component, with demo props
// and theming flags. Regenerated from the component sources; avoid hand-edits.
export interface GalleryItem {
  name: string
  category: string
  blurb: string
  props: Record<string, unknown>
  /** Whether the component wraps children (the gallery injects a sample). */
  child?: boolean
  /** Reads the active theme (re-skins with the gallery's theme switcher). */
  themed?: boolean
  /** If set, the in-browser engine can't preview this yet — show this note. */
  note?: string
}

export const GALLERY_CATEGORIES = [
  'Entrances',
  'Exits',
  'Text reveals',
  'Text effects',
  'Cards',
  'Overlays & UI',
  'Mockups',
  'Data',
  'Media',
  'Backgrounds & FX',
] as const

export const GALLERY: GalleryItem[] = [
  {
    name: 'BlurReveal',
    category: 'Entrances',
    blurb: 'the reference Onda reveal: opacity + a small rise + a subtle',
    props: {
      text: 'Onda',
      fontSize: 140,
      fontWeight: 600,
      durationInFrames: 24,
      placement: 'center',
    },
    child: true,
    themed: true,
  },
  {
    name: 'FadeIn',
    category: 'Entrances',
    blurb: 'pure opacity reveal (no motion). Layout-safe: applies only opacity,',
    props: {},
    child: true,
  },
  {
    name: 'MaskReveal',
    category: 'Entrances',
    blurb: 'a hard-edge mask reveal: content uncovered by a clip region that',
    props: {
      text: 'Onda',
      direction: 'left',
      fontSize: 120,
      fontWeight: 600,
      duration: 24,
    },
    themed: true,
  },
  {
    name: 'RotateIn',
    category: 'Entrances',
    blurb: 'opacity + rotation from `fromDegrees` → 0° on the house spring',
    props: {
      fromDegrees: -8,
      delay: 0,
      durationInFrames: 18,
    },
    child: true,
  },
  {
    name: 'ScaleIn',
    category: 'Entrances',
    blurb: 'opacity + scale from `from` → 1 on the house spring. Restrained by',
    props: {
      from: 0.6,
    },
    child: true,
  },
  {
    name: 'SlideIn',
    category: 'Entrances',
    blurb: 'directional translate + fade on the house spring. `direction` names',
    props: {
      direction: 'up',
      distance: 48,
    },
    child: true,
  },
  {
    name: 'FadeOut',
    category: 'Exits',
    blurb: 'opacity 1 → 0 on the house ease. The exit counterpart to FadeIn;',
    props: {
      delay: 34,
    },
    child: true,
  },
  {
    name: 'SlideOut',
    category: 'Exits',
    blurb: 'directional translate + fade out on the house ease. `direction`',
    props: {
      delay: 34,
      direction: 'down',
      distance: 48,
    },
    child: true,
  },
  {
    name: 'CountUp',
    category: 'Text reveals',
    blurb: 'an animated number that counts from `from` to `to`. Ported from ondajs',
    props: {
      from: 0,
      to: 12847,
      prefix: '$',
      suffix: '+',
      decimals: 0,
      fontSize: 140,
      fontWeight: 700,
      x: 120,
      y: 360,
      durationInFrames: 24,
    },
    themed: true,
  },
  {
    name: 'MatrixDecode',
    category: 'Text reveals',
    blurb: 'glyphs flicker through random chars then settle left-to-right,',
    props: {
      text: 'DECODE',
      fontSize: 140,
      fontWeight: 700,
      scrambleDuration: 24,
      charDelay: 4,
      scrambleSpeed: 2,
      seed: 7,
      align: 'center',
    },
    themed: true,
  },
  {
    name: 'TextFadeReplace',
    category: 'Text reveals',
    blurb: 'crossfade between an old and a new phrase in place. Ported from ondajs',
    props: {
      from: 'ship',
      to: 'render',
      delay: 30,
      durationInFrames: 18,
      fontSize: 120,
      fontWeight: 600,
    },
    themed: true,
  },
  {
    name: 'TrackingIn',
    category: 'Text reveals',
    blurb: 'letter-spacing tighten + fade. Ported from ondajs',
    props: {
      text: 'ONDA',
      fontSize: 140,
      fontWeight: 600,
      fromTracking: 0.55,
      tracking: -0.02,
      blur: true,
      align: 'center',
    },
    themed: true,
  },
  {
    name: 'Typewriter',
    category: 'Text reveals',
    blurb: 'reveal text character-by-character with an optional blinking',
    props: {
      text: 'motion graphics',
      durationInFrames: 24,
      cursor: true,
      fontSize: 80,
      fontWeight: 500,
    },
    themed: true,
  },
  {
    name: 'WordRotate',
    category: 'Text reveals',
    blurb: 'cycle a list of phrases in place, one at a time. Ported from ondajs',
    props: {
      phrases: ['fast', 'beautiful', 'restrained'],
      align: 'center',
      fontSize: 120,
      fontWeight: 600,
      holdDuration: 30,
      transitionDuration: 12,
    },
    themed: true,
  },
  {
    name: 'WordStagger',
    category: 'Text reveals',
    blurb: 'split a phrase into words and reveal them left-to-right with a',
    props: {
      text: 'motion that moves you',
      fontSize: 96,
      width: 1080,
      fontWeight: 600,
      justify: 'center',
      stagger: 4,
    },
    themed: true,
  },
  {
    name: 'GradientShift',
    category: 'Text effects',
    blurb: 'a quiet, drifting two-color linear gradient background whose',
    props: {
      angle: 135,
      speed: 0.8,
      delay: 0,
    },
    themed: true,
  },
  {
    name: 'Highlight',
    category: 'Text effects',
    blurb: 'marker-style background reveal. Ported from ondajs',
    props: {
      text: 'motion graphics',
      fontSize: 72,
      fontWeight: 600,
      paddingX: 10,
      x: 120,
      y: 120,
    },
    themed: true,
  },
  {
    name: 'RgbGlitch',
    category: 'Text effects',
    blurb: 'RGB channel-split glitch text. Ported from ondajs (rgb-glitch-text)',
    props: {
      text: 'SIGNAL',
      fontSize: 160,
      intensity: 14,
      baseSplit: 3,
    },
    themed: true,
  },
  {
    name: 'ShimmerSweep',
    category: 'Text effects',
    blurb: 'a single bright band of light sweeps across text. Ported from ondajs',
    props: {
      text: 'Shipping today',
      fontSize: 120,
      fontWeight: 600,
      duration: 36,
      x: 320,
      y: 300,
    },
    themed: true,
  },
  {
    name: 'SlotMachineRoll',
    category: 'Text effects',
    blurb: 'each character spins down a reel of glyphs and lands on its',
    props: {
      text: '2026',
      fontSize: 180,
      fontWeight: 700,
      reelLength: 14,
      charDelay: 5,
      seed: 7,
    },
    themed: true,
  },
  {
    name: 'Underline',
    category: 'Text effects',
    blurb: 'text fades in, then a rounded accent rule draws beneath it,',
    props: {
      text: 'motion graphics',
      fontSize: 96,
      lineThickness: 4,
      lineOffset: 10,
      delay: 0,
      duration: 18,
      lineDelay: 8,
      lineDuration: 10,
    },
    themed: true,
  },
  {
    name: 'BentoGrid',
    category: 'Cards',
    blurb: 'a data-driven bento layout: a grid of glass cards with varying',
    props: {
      columns: 3,
      width: 960,
      gap: 20,
      items: [
        {
          title: 'Motion identity',
          caption: 'One consistent feel across every component.',
          colSpan: 2,
          rowSpan: 1,
        },
        {
          title: 'Render',
          value: '4K',
          caption: 'Deterministic, frame-perfect.',
          colSpan: 1,
          rowSpan: 1,
          accent: true,
        },
        {
          title: 'Components',
          value: '40+',
          caption: 'Copied into your project.',
          colSpan: 1,
          rowSpan: 1,
        },
        {
          title: 'Spring physics',
          caption: 'No overshoot. Calm by default.',
          colSpan: 2,
          rowSpan: 1,
        },
      ],
    },
    themed: true,
  },
  {
    name: 'ChapterCard',
    category: 'Cards',
    blurb: 'a numbered eyebrow ("01") fades in above a large chapter title',
    props: {
      chapter: 'The setup',
      number: '01',
      accent: true,
      delay: 0,
      titleFontSize: 110,
      numberFontSize: 34,
    },
    themed: true,
  },
  {
    name: 'EndCard',
    category: 'Cards',
    blurb: 'closing outro/credits block. A hero CTA reveals (with an optional',
    props: {
      cta: 'Made with Onda',
      handles: ['@onda.video', 'onda.video/components'],
      accent: true,
      ctaFontSize: 96,
      ctaFontWeight: 600,
      handlesFontSize: 24,
    },
    themed: true,
  },
  {
    name: 'PricingCard',
    category: 'Cards',
    blurb: 'a single pricing tier: a rounded glass panel with the tier',
    props: {
      tier: 'Pro',
      price: '$29',
      period: '/month',
      features: [
        'Unlimited renders',
        'Signature motion identity',
        'Source you own, copied in',
        'Priority support',
      ],
      cta: 'Get started',
      recommended: true,
      priceSize: 64,
      width: 380,
    },
    themed: true,
  },
  {
    name: 'QuoteCard',
    category: 'Cards',
    blurb: 'a centered pull-quote: a large word-staggered quote, an accent',
    props: {
      quote: 'Design is intelligence made visible.',
      author: 'Alina Wheeler',
      role: 'Brand Designer',
      accent: true,
      quoteFontSize: 56,
      authorFontSize: 24,
      delay: 0,
    },
    themed: true,
  },
  {
    name: 'SkeletonCard',
    category: 'Cards',
    blurb: 'a loading-placeholder card: an optional thumbnail block plus a',
    props: {
      lines: 4,
      thumbnail: true,
      shimmerSpeed: 48,
      width: 520,
      barHeight: 20,
    },
    themed: true,
  },
  {
    name: 'SpotlightCard',
    category: 'Cards',
    blurb: 'a glass card with a spotlight drifting behind the content,',
    props: {
      eyebrow: 'FEATURE',
      title: 'Motion identity',
      body: 'One consistent feel across every component.',
      width: 560,
      padding: 48,
      align: 'left',
    },
    themed: true,
  },
  {
    name: 'StatCard',
    category: 'Cards',
    blurb: 'a single metric: a big value, a label beneath it, and a short',
    props: {
      value: '9.3×',
      label: 'faster than Remotion',
    },
    themed: true,
  },
  {
    name: 'TitleCard',
    category: 'Cards',
    blurb: 'a centered title with an optional subtitle, each fading in with a',
    props: {
      title: 'ONDA',
      subtitle: 'GPU-native motion graphics',
    },
    themed: true,
  },
  {
    name: 'BoundingBox',
    category: 'Overlays & UI',
    blurb: 'a stroked rectangle outline that reveals around a region, with',
    props: {
      x: 0.28,
      y: 0.3,
      width: 0.44,
      height: 0.4,
      label: 'Settings',
      strokeWidth: 3,
      cornerRadius: 0,
      corners: true,
      labelColor: '#08080a',
      fontSize: 18,
      delay: 0,
      drawDuration: 24,
    },
    themed: true,
  },
  {
    name: 'Button',
    category: 'Overlays & UI',
    blurb: 'a styled CTA pill: a rounded filled `<Rect>` with a centered label',
    props: {
      label: 'Get started',
      variant: 'primary',
      width: 320,
      height: 80,
      fontSize: 30,
      fontWeight: 600,
      delay: 6,
      press: true,
      pressFrame: 36,
    },
    themed: true,
  },
  {
    name: 'Callout',
    category: 'Overlays & UI',
    blurb: 'a speech bubble (rounded `<Rect>` body + pointer triangle `<Path>` +',
    props: {
      label: 'Tap here',
      x: 0.5,
      y: 0.5,
      direction: 'bottom',
      fontSize: 32,
      delay: 0,
      duration: 18,
      lineDelay: 6,
    },
    themed: true,
  },
  {
    name: 'Captions',
    category: 'Overlays & UI',
    blurb: 'sequential word-by-word captions driven by a timed transcript',
    props: {
      captions: [
        {
          text: 'Render',
          startMs: 0,
          endMs: 700,
        },
        {
          text: 'motion',
          startMs: 700,
          endMs: 1400,
        },
        {
          text: 'graphics',
          startMs: 1400,
          endMs: 2100,
        },
        {
          text: 'without',
          startMs: 2100,
          endMs: 2700,
        },
        {
          text: 'a',
          startMs: 2700,
          endMs: 3000,
        },
        {
          text: 'browser',
          startMs: 3000,
          endMs: 4200,
        },
      ],
      fontSize: 88,
      fontWeight: 600,
      align: 'center',
      placement: 'lower-third',
      maxWidth: 0.82,
    },
    themed: true,
  },
  {
    name: 'Cursor',
    category: 'Overlays & UI',
    blurb: 'an animated mouse pointer that travels between two canvas points on',
    props: {
      fromX: 0.25,
      fromY: 0.72,
      toX: 0.62,
      toY: 0.4,
      delay: 6,
      travelDuration: 24,
      click: true,
      clickDelay: 6,
      size: 72,
    },
    themed: true,
  },
  {
    name: 'IconPop',
    category: 'Overlays & UI',
    blurb: 'an icon (a glyph/emoji or a built-in shape) popping into place with',
    props: {
      glyph: '✦',
      iconSize: 220,
      x: 640,
      y: 360,
      overshoot: 0.22,
      durationInFrames: 18,
    },
    themed: true,
  },
  {
    name: 'InputField',
    category: 'Overlays & UI',
    blurb: 'a UI text-input mockup. Ported from ondajs (`input-field`)',
    props: {
      value: 'hello@onda.video',
      placeholder: 'Enter your email',
      label: 'Email',
      typed: true,
      delay: 6,
      typeDuration: 40,
      focusRing: true,
      width: 640,
      fontSize: 40,
    },
    themed: true,
  },
  {
    name: 'LowerThird',
    category: 'Overlays & UI',
    blurb: 'broadcast-style name + role bar that slides + fades into a corner',
    props: {
      name: 'Rodrigo Silva',
      role: 'Founder & CEO, ONDA',
      placement: 'bottom-left',
      accent: true,
      fontSize: 54,
      roleFontSize: 24,
    },
    themed: true,
  },
  {
    name: 'PulsingIndicator',
    category: 'Overlays & UI',
    blurb: 'a live status dot with a calm expanding-ring pulse, plus an',
    props: {
      size: 40,
      label: 'LIVE',
      fontSize: 48,
      period: 45,
    },
    themed: true,
  },
  {
    name: 'BrowserFrame',
    category: 'Mockups',
    blurb: 'a browser-window chrome that wraps arbitrary content. A top',
    props: {
      url: 'onda.video/render',
      src: 'DEMO_IMAGE',
      width: 1024,
      height: 560,
      delay: 0,
      animate: true,
    },
    child: true,
    themed: true,
  },
  {
    name: 'CodeBlock',
    category: 'Mockups',
    blurb: 'syntax-highlighted source on a dark rounded panel, revealed',
    props: {
      code: "import { motion } from '@onda/react';\n\nexport const Hero = () => {\n  const x = 100; // accent demo\n  return <Group x={x}>Hello</Group>;\n};",
      title: 'hero.tsx',
      chrome: true,
      revealLines: true,
      lineDelay: 4,
      fontSize: 40,
      width: 980,
    },
    themed: true,
  },
  {
    name: 'CodeDiff',
    category: 'Mockups',
    blurb: 'a unified code diff panel, revealed line-by-line. Added / removed',
    props: {
      lines: [
        {
          text: 'function render(scene) {',
          type: 'context',
        },
        {
          text: '  const dom = browser.launch();',
          type: 'remove',
        },
        {
          text: '  const gpu = vello.surface();',
          type: 'add',
        },
        {
          text: '  return gpu.draw(scene);',
          type: 'add',
        },
        {
          text: '}',
          type: 'context',
        },
      ],
      title: 'renderer.ts',
      fontSize: 38,
      width: 820,
      chrome: true,
      revealLines: true,
      lineDelay: 4,
    },
    themed: true,
  },
  {
    name: 'DeviceFrame',
    category: 'Mockups',
    blurb: 'a phone or laptop bezel wrapping arbitrary content. Ported from ondajs',
    props: {
      device: 'phone',
      src: 'DEMO_IMAGE',
      width: 360,
      animate: true,
      delay: 0,
    },
    child: false,
    themed: true,
  },
  {
    name: 'DynamicGrid',
    category: 'Mockups',
    blurb: 'a technical grid that drifts diagonally, an optional centered',
    props: {
      variant: 'lines',
      cell: 64,
      speed: 0.4,
      opacity: 0.7,
      glow: true,
      thickness: 1.5,
    },
    themed: true,
  },
  {
    name: 'KanbanBoard',
    category: 'Mockups',
    blurb: 'a data-driven board: a row of glass columns, each with a header',
    props: {
      columns: [
        {
          title: 'Todo',
          cards: ['Storyboard the intro', 'Source b-roll', 'Write VO script'],
        },
        {
          title: 'In Progress',
          accent: '#d96b82',
          cards: ['Animate the title card', 'Color-grade scene 2'],
        },
        {
          title: 'Done',
          cards: ['Lock the edit', 'Render preview', 'Sound pass', 'Export master'],
        },
      ],
      width: 1040,
      gap: 20,
      stagger: 4,
      fontSize: 22,
    },
    themed: true,
  },
  {
    name: 'SplitScreen',
    category: 'Mockups',
    blurb: 'two side-by-side (or stacked) content panes divided by a thin',
    props: {
      orientation: 'horizontal',
      ratio: 0.5,
      gap: 2,
      divider: true,
      animate: true,
      delay: 0,
      width: 1120,
      height: 600,
    },
    themed: true,
  },
  {
    name: 'StaggerGroup',
    category: 'Mockups',
    blurb: 'reveals a list of items in sequence on the canonical Onda',
    props: {
      items: ['Less is more', 'Calm is power', 'Motion has a feel', 'Made to be edited'],
      direction: 'column',
      align: 'center',
      gap: 24,
      stagger: 6,
      duration: 18,
      fontSize: 72,
      fontWeight: 600,
    },
    themed: true,
  },
  {
    name: 'Terminal',
    category: 'Mockups',
    blurb: 'a terminal session window. Ported from ondajs',
    props: {
      command: 'npx ondajs add code-block',
      output: ['✓ added code-block', '✓ wrote 4 files', '✓ done in 1.2s'],
      prompt: '$',
      title: 'zsh — onda',
      typeSpeed: 30,
      fontSize: 44,
      width: 920,
    },
    themed: true,
  },
  {
    name: 'BarChart',
    category: 'Data',
    blurb: 'horizontal bars that grow from 0 to their value on the house',
    props: {
      data: [
        {
          label: 'Remotion',
          value: 92,
        },
        {
          label: 'After Effects',
          value: 64,
        },
        {
          label: 'Lottie',
          value: 38,
        },
      ],
      max: 100,
      showValues: true,
      barHeight: 40,
      gap: 24,
      fontSize: 26,
      labelWidth: 240,
      trackWidth: 760,
    },
    themed: true,
  },
  {
    name: 'LineChart',
    category: 'Data',
    blurb: 'a polyline that draws on left-to-right on the house easing, with',
    props: {
      data: [12, 18, 15, 24, 22, 31, 28, 38, 34, 44],
      strokeWidth: 4,
      width: 980,
      height: 460,
      fill: true,
      showDots: true,
      duration: 40,
      delay: 4,
    },
    themed: true,
  },
  {
    name: 'NodeGraph',
    category: 'Data',
    blurb: 'a hub-and-spoke constellation: a labeled central hub with',
    props: {
      hubLabel: 'AI',
      glow: true,
      centerX: 0.5,
      centerY: 0.5,
    },
    themed: true,
  },
  {
    name: 'PieReveal',
    category: 'Data',
    blurb: 'a pie/donut chart whose slices grow from 0. Each slice is a',
    props: {
      data: [
        {
          value: 48,
          color: '#d96b82',
          label: 'Onda',
        },
        {
          value: 27,
          color: '#5b8def',
          label: 'Remotion',
        },
        {
          value: 15,
          color: '#f2c14e',
          label: 'Lottie',
        },
        {
          value: 10,
          color: '#3a3a44',
          label: 'Other',
        },
      ],
      radius: 200,
      innerRadius: 110,
      showLabel: true,
      label: '4',
      fontSize: 80,
      duration: 24,
      stagger: 5,
    },
    themed: true,
  },
  {
    name: 'ProgressBar',
    category: 'Data',
    blurb: 'a horizontal bar that fills from 0 to `value`% on the house',
    props: {
      value: 72,
      width: 720,
      height: 16,
      fontSize: 32,
      showValue: true,
    },
    themed: true,
  },
  {
    name: 'ProgressSteps',
    category: 'Data',
    blurb: 'a horizontal stepper whose fill travels to the `current` step',
    props: {
      steps: ['Plan', 'Build', 'Render', 'Ship'],
      current: 2,
      width: 900,
      fontSize: 34,
      dotSize: 30,
    },
    themed: true,
  },
  {
    name: 'Timeline',
    category: 'Data',
    blurb: 'a vertical event timeline. Ported from ondajs (`timeline`)',
    props: {
      events: [
        {
          label: 'Concept',
        },
        {
          label: 'Build',
        },
        {
          label: 'Ship',
        },
        {
          label: 'Iterate',
        },
      ],
      spacing: 130,
      dotSize: 20,
      fontSize: 30,
    },
    themed: true,
  },
  {
    name: 'AudioClip',
    category: 'Media',
    blurb: 'audio scheduling primitive. Ported from ondajs',
    props: {
      src: 'https://www.w3schools.com/html/horse.mp3',
      startAt: 0,
      volume: 1,
    },
    note: "Audio is non-visual — it schedules a track through the engine's audio pipeline.",
  },
  {
    name: 'AudioVisualizer',
    category: 'Media',
    blurb: 'a frequency-bar spectrum visualizer. Ported from ondajs',
    props: {
      barCount: 56,
      color: ['#d96b82', '#7c5ce5'],
      width: 920,
      height: 280,
      align: 'middle',
      gap: 5,
      speed: 1,
      seed: 7,
    },
    themed: true,
  },
  {
    name: 'ImageReveal',
    category: 'Media',
    blurb: "an image that enters with one of Onda's signature motion",
    props: {
      src: '/gallery-sample.png',
      motion: 'wipe',
      fit: 'cover',
      durationInFrames: 24,
      srcWidth: 1280,
      srcHeight: 720,
    },
    themed: true,
    note: 'In-browser image decoding is not wired up yet — renders from a file via `onda render`.',
  },
  {
    name: 'KenBurns',
    category: 'Media',
    blurb: 'a slow cinematic zoom + pan over a photo (the iconic documentary',
    props: {
      src: '/gallery-sample.png',
      imageWidth: 1920,
      imageHeight: 1080,
      duration: 150,
      fromScale: 1,
      toScale: 1.15,
      fromX: 0.3,
      fromY: 0.35,
      toX: 0.7,
      toY: 0.6,
    },
    note: 'Needs a source image; in-browser image decoding is not wired up yet (renders via `onda render`).',
  },
  {
    name: 'Parallax',
    category: 'Media',
    blurb: 'slow, linear drift of one or more image layers at different rates',
    props: {
      layers: [
        {
          src: 'DEMO_IMAGE',
          speed: 0.4,
          scale: 1.08,
          opacity: 0.55,
        },
        {
          src: 'DEMO_IMAGE',
          speed: 1,
          scale: 1.05,
        },
      ],
      direction: 'left',
      distance: 80,
      duration: 180,
      delay: 0,
      src: '/gallery-sample.png',
    },
    note: 'Needs source image layers; in-browser image decoding is not wired up yet.',
  },
  {
    name: 'VideoClip',
    category: 'Media',
    blurb: 'a trimmed video clip with the Onda fade envelope. Ported from ondajs',
    props: {
      src: '/gallery-sample.png',
      fadeIn: 18,
      fadeOut: 18,
      durationInFrames: 90,
      fit: 'cover',
      letterbox: 60,
      borderRadius: 12,
    },
    themed: true,
    note: 'Video decode is not in the engine yet — renders a poster frame via `onda render`.',
  },
  {
    name: 'CameraShake',
    category: 'Backgrounds & FX',
    blurb: 'wraps children in a deterministic, decaying camera shake',
    props: {
      intensity: 14,
      rotationIntensity: 1.2,
      duration: 60,
      decay: false,
      seed: 7,
      x: 640,
      y: 360,
    },
    child: true,
  },
  {
    name: 'Confetti',
    category: 'Backgrounds & FX',
    blurb: 'a celebratory particle burst over the whole canvas. Ported from ondajs',
    props: {
      seed: 7,
      count: 90,
      colors: ['#d96b82', '#e89aab', '#f2f2f4', '#8e8e98', '#5b8def'],
      originX: 0.5,
      originY: 0.45,
      delay: 0,
      duration: 70,
      spread: 130,
      gravity: 1,
      pieceSize: 14,
    },
    themed: true,
  },
  {
    name: 'DrawOn',
    category: 'Backgrounds & FX',
    blurb: 'an SVG path that "draws on", the substrate for logos, icons, and',
    props: {
      d: 'M 80 360 C 240 80, 520 80, 640 360 S 1040 640, 1200 360',
      strokeWidth: 10,
      durationInFrames: 30,
    },
    themed: true,
  },
  {
    name: 'GrainOverlay',
    category: 'Backgrounds & FX',
    blurb: 'a subtle film-grain texture layered over the whole canvas',
    props: {
      opacity: 0.12,
      baseFrequency: 0.7,
      numOctaves: 3,
      seed: 7,
      count: 900,
    },
    themed: true,
  },
  {
    name: 'LogoSting',
    category: 'Backgrounds & FX',
    blurb: 'a silent, restrained branded reveal: a logo mark wipes in, a title',
    props: {
      d: 'M 20 80 Q 80 10 150 70 T 280 60',
      title: 'Onda',
      viewBox: '0 0 300 120',
      pathWidth: 460,
      pathHeight: 180,
      strokeWidth: 5,
      titleFontSize: 104,
      accent: true,
      delay: 0,
    },
    themed: true,
  },
  {
    name: 'Marquee',
    category: 'Backgrounds & FX',
    blurb: 'a seamless looping horizontal scroll (logo strips, ticker tape,',
    props: {
      items: ['ONDA', 'TYPESCRIPT', 'REACT', 'GPU NATIVE', 'VELLO'],
      speed: 60,
      direction: 'left',
      gap: 80,
      fontSize: 64,
      fontWeight: 600,
      height: 120,
    },
    themed: true,
  },
  {
    name: 'MeshGradient',
    category: 'Backgrounds & FX',
    blurb: 'a drifting mesh-gradient backdrop. Ported from ondajs',
    props: {
      speed: 1.2,
      seed: 7,
      opacity: 0.7,
    },
    themed: true,
  },
  {
    name: 'Spotlight',
    category: 'Backgrounds & FX',
    blurb: 'a soft radial light that grows from radius 0 to its target on the',
    props: {
      x: 0.5,
      y: 0.45,
      radius: 45,
      delay: 0,
      durationInFrames: 24,
      softness: 65,
    },
    themed: true,
  },
  {
    name: 'Vignette',
    category: 'Backgrounds & FX',
    blurb: 'a static cinematic darkening at the canvas edges that pulls the',
    props: {
      intensity: 0.7,
      innerRadius: 35,
    },
    themed: true,
  },
]
