import { Composition, type Scene, Text, renderFrame } from '@onda/react'
import type { FunctionComponent } from 'react'
import { createElement as h } from 'react'
import { describe, expect, it } from 'vitest'
import * as Lib from './index.js'

// Generated from the verified demo cases — a regression guard that every ported
// component renders to a non-empty scene without throwing, at the frame used to
// visually verify it. (Visual correctness was checked by rendering each via the
// Vello backend; this keeps them from silently breaking.)
const CASES: { name: string; frame: number; props: Record<string, unknown> }[] = [
  {
    name: 'AudioClip',
    frame: 0,
    props: {
      src: 'https://www.w3schools.com/html/horse.mp3',
      startAt: 0,
      volume: 1,
    },
  },
  {
    name: 'AudioVisualizer',
    frame: 48,
    props: {
      barCount: 56,
      color: ['#d96b82', '#7c5ce5'],
      width: 920,
      height: 280,
      align: 'middle',
      gap: 5,
      speed: 1,
      seed: 7,
    },
  },
  {
    name: 'BarChart',
    frame: 48,
    props: {
      data: [
        {
          label: 'Remotion',
          value: 92,
        },
        {
          label: 'After Effects',
          value: 64,
        },
        {
          label: 'Lottie',
          value: 38,
        },
      ],
      max: 100,
      showValues: true,
      accentColor: '#d96b82',
      barColor: '#8e8e98',
      trackColor: '#1c1c22',
      color: '#f2f2f4',
      barHeight: 40,
      gap: 24,
      fontSize: 26,
      labelWidth: 240,
      trackWidth: 760,
    },
  },
  {
    name: 'BentoGrid',
    frame: 30,
    props: {
      columns: 3,
      width: 960,
      gap: 20,
      items: [
        {
          title: 'Motion identity',
          caption: 'One consistent feel across every component.',
          colSpan: 2,
          rowSpan: 1,
        },
        {
          title: 'Render',
          value: '4K',
          caption: 'Deterministic, frame-perfect.',
          colSpan: 1,
          rowSpan: 1,
          accent: true,
        },
        {
          title: 'Components',
          value: '40+',
          caption: 'Copied into your project.',
          colSpan: 1,
          rowSpan: 1,
        },
        {
          title: 'Spring physics',
          caption: 'No overshoot. Calm by default.',
          colSpan: 2,
          rowSpan: 1,
        },
      ],
    },
  },
  {
    name: 'BlurReveal',
    frame: 20,
    props: {
      text: 'Onda',
      fontSize: 140,
      color: '#f2f2f4',
      fontWeight: 600,
      durationInFrames: 24,
      placement: 'center',
    },
  },
  {
    name: 'BoundingBox',
    frame: 40,
    props: {
      x: 0.28,
      y: 0.3,
      width: 0.44,
      height: 0.4,
      label: 'Settings',
      color: '#d96b82',
      strokeWidth: 3,
      cornerRadius: 0,
      corners: true,
      labelColor: '#08080a',
      fontSize: 18,
      delay: 0,
      drawDuration: 24,
    },
  },
  {
    name: 'BrowserFrame',
    frame: 20,
    props: {
      url: 'onda.video/render',
      src: 'DEMO_IMAGE',
      width: 1024,
      height: 560,
      delay: 0,
      animate: true,
    },
  },
  {
    name: 'Button',
    frame: 36,
    props: {
      label: 'Get started',
      variant: 'primary',
      color: '#d96b82',
      textColor: '#08080a',
      width: 320,
      height: 80,
      fontSize: 30,
      fontWeight: 600,
      delay: 6,
      press: true,
      pressFrame: 36,
    },
  },
  {
    name: 'Callout',
    frame: 40,
    props: {
      label: 'Tap here',
      x: 0.5,
      y: 0.5,
      direction: 'bottom',
      fontSize: 32,
      delay: 0,
      duration: 18,
      lineDelay: 6,
    },
  },
  {
    name: 'CameraShake',
    frame: 12,
    props: {
      intensity: 14,
      rotationIntensity: 1.2,
      duration: 60,
      decay: false,
      seed: 7,
      x: 640,
      y: 360,
    },
  },
  {
    name: 'Captions',
    frame: 60,
    props: {
      captions: [
        {
          text: 'Render',
          startMs: 0,
          endMs: 700,
        },
        {
          text: 'motion',
          startMs: 700,
          endMs: 1400,
        },
        {
          text: 'graphics',
          startMs: 1400,
          endMs: 2100,
        },
        {
          text: 'without',
          startMs: 2100,
          endMs: 2700,
        },
        {
          text: 'a',
          startMs: 2700,
          endMs: 3000,
        },
        {
          text: 'browser',
          startMs: 3000,
          endMs: 4200,
        },
      ],
      fontSize: 88,
      fontWeight: 600,
      color: '#8e8e98',
      accentColor: '#f2f2f4',
      align: 'center',
      placement: 'lower-third',
      maxWidth: 0.82,
    },
  },
  {
    name: 'ChapterCard',
    frame: 60,
    props: {
      chapter: 'The setup',
      number: '01',
      accent: true,
      delay: 0,
      titleFontSize: 110,
      numberFontSize: 34,
    },
  },
  {
    name: 'CodeBlock',
    frame: 40,
    props: {
      code: "import { motion } from '@onda/react';\n\nexport const Hero = () => {\n  const x = 100; // accent demo\n  return <Group x={x}>Hello</Group>;\n};",
      title: 'hero.tsx',
      chrome: true,
      revealLines: true,
      lineDelay: 4,
      fontSize: 40,
      width: 980,
    },
  },
  {
    name: 'CodeDiff',
    frame: 40,
    props: {
      lines: [
        {
          text: 'function render(scene) {',
          type: 'context',
        },
        {
          text: '  const dom = browser.launch();',
          type: 'remove',
        },
        {
          text: '  const gpu = vello.surface();',
          type: 'add',
        },
        {
          text: '  return gpu.draw(scene);',
          type: 'add',
        },
        {
          text: '}',
          type: 'context',
        },
      ],
      title: 'renderer.ts',
      fontSize: 38,
      width: 820,
      chrome: true,
      revealLines: true,
      lineDelay: 4,
    },
  },
  {
    name: 'Confetti',
    frame: 22,
    props: {
      seed: 7,
      count: 90,
      colors: ['#d96b82', '#e89aab', '#f2f2f4', '#8e8e98', '#5b8def'],
      originX: 0.5,
      originY: 0.45,
      delay: 0,
      duration: 70,
      spread: 130,
      gravity: 1,
      pieceSize: 14,
    },
  },
  {
    name: 'CountUp',
    frame: 16,
    props: {
      from: 0,
      to: 12847,
      prefix: '$',
      suffix: '+',
      decimals: 0,
      fontSize: 140,
      fontWeight: 700,
      color: '#F2F2F4',
      x: 120,
      y: 360,
      durationInFrames: 24,
    },
  },
  {
    name: 'Cursor',
    frame: 40,
    props: {
      fromX: 0.25,
      fromY: 0.72,
      toX: 0.62,
      toY: 0.4,
      delay: 6,
      travelDuration: 24,
      click: true,
      clickDelay: 6,
      color: '#f2f2f4',
      size: 72,
    },
  },
  {
    name: 'DeviceFrame',
    frame: 30,
    props: {
      device: 'phone',
      src: 'DEMO_IMAGE',
      width: 360,
      animate: true,
      delay: 0,
    },
  },
  {
    name: 'DrawOn',
    frame: 22,
    props: {
      d: 'M 80 360 C 240 80, 520 80, 640 360 S 1040 640, 1200 360',
      color: '#d96b82',
      strokeWidth: 10,
      durationInFrames: 30,
    },
  },
  {
    name: 'DynamicGrid',
    frame: 40,
    props: {
      variant: 'lines',
      cell: 64,
      color: '#2a2a33',
      speed: 0.4,
      opacity: 0.7,
      glow: true,
      glowColor: '#d96b82',
      background: '#08080a',
      thickness: 1.5,
    },
  },
  {
    name: 'EndCard',
    frame: 52,
    props: {
      cta: 'Made with Onda',
      handles: ['@onda.video', 'onda.video/components'],
      accent: true,
      ctaFontSize: 96,
      ctaFontWeight: 600,
      handlesFontSize: 24,
      color: '#f2f2f4',
      handlesColor: '#9aa4b2',
      accentColor: '#d96b82',
    },
  },
  {
    name: 'GradientShift',
    frame: 45,
    props: {
      from: '#2A1A4A',
      to: '#0E2A3A',
      angle: 135,
      speed: 0.8,
      delay: 0,
    },
  },
  {
    name: 'GrainOverlay',
    frame: 0,
    props: {
      opacity: 0.12,
      baseFrequency: 0.7,
      numOctaves: 3,
      seed: 7,
      count: 900,
      color: '#f2f2f4',
    },
  },
  {
    name: 'Highlight',
    frame: 36,
    props: {
      text: 'motion graphics',
      fontSize: 72,
      color: '#f2f2f4',
      accentColor: '#d96b82',
      fontWeight: 600,
      paddingX: 10,
      x: 120,
      y: 120,
    },
  },
  {
    name: 'IconPop',
    frame: 4,
    props: {
      glyph: '✦',
      iconSize: 220,
      color: '#d96b82',
      x: 640,
      y: 360,
      overshoot: 0.22,
      durationInFrames: 18,
    },
  },
  {
    name: 'ImageReveal',
    frame: 12,
    props: {
      src: 'DEMO_IMAGE',
      motion: 'wipe',
      fit: 'cover',
      durationInFrames: 24,
      srcWidth: 1280,
      srcHeight: 720,
    },
  },
  {
    name: 'InputField',
    frame: 34,
    props: {
      value: 'hello@onda.video',
      placeholder: 'Enter your email',
      label: 'Email',
      typed: true,
      delay: 6,
      typeDuration: 40,
      focusRing: true,
      width: 640,
      fontSize: 40,
    },
  },
  {
    name: 'KanbanBoard',
    frame: 55,
    props: {
      columns: [
        {
          title: 'Todo',
          cards: ['Storyboard the intro', 'Source b-roll', 'Write VO script'],
        },
        {
          title: 'In Progress',
          accent: '#d96b82',
          cards: ['Animate the title card', 'Color-grade scene 2'],
        },
        {
          title: 'Done',
          cards: ['Lock the edit', 'Render preview', 'Sound pass', 'Export master'],
        },
      ],
      width: 1040,
      gap: 20,
      stagger: 4,
      fontSize: 22,
    },
  },
  {
    name: 'KenBurns',
    frame: 120,
    props: {
      src: 'DEMO_IMAGE',
      imageWidth: 1920,
      imageHeight: 1080,
      duration: 150,
      fromScale: 1,
      toScale: 1.15,
      fromX: 0.3,
      fromY: 0.35,
      toX: 0.7,
      toY: 0.6,
    },
  },
  {
    name: 'KineticText',
    frame: 18,
    props: {
      text: 'kinetic',
      fontSize: 140,
      preset: 'blur',
      color: '#f2f2f4',
      fontWeight: 600,
      align: 'center',
      stagger: 5,
      durationInFrames: 22,
    },
  },
  {
    name: 'LineChart',
    frame: 36,
    props: {
      data: [12, 18, 15, 24, 22, 31, 28, 38, 34, 44],
      color: '#d96b82',
      strokeWidth: 4,
      width: 980,
      height: 460,
      fill: true,
      showDots: true,
      duration: 40,
      delay: 4,
    },
  },
  {
    name: 'LogoSting',
    frame: 42,
    props: {
      d: 'M 20 80 Q 80 10 150 70 T 280 60',
      title: 'Onda',
      viewBox: '0 0 300 120',
      pathWidth: 460,
      pathHeight: 180,
      strokeWidth: 5,
      stroke: '#f2f2f4',
      accentColor: '#d96b82',
      titleFontSize: 104,
      color: '#f2f2f4',
      accent: true,
      delay: 0,
    },
  },
  {
    name: 'LowerThird',
    frame: 30,
    props: {
      name: 'Rodrigo Silva',
      role: 'Founder & CEO, ONDA',
      placement: 'bottom-left',
      accent: true,
      color: '#f2f2f4',
      roleColor: '#8e8e98',
      accentColor: '#d96b82',
      fontSize: 54,
      roleFontSize: 24,
    },
  },
  {
    name: 'Marquee',
    frame: 75,
    props: {
      items: ['ONDA', 'TYPESCRIPT', 'REACT', 'GPU NATIVE', 'VELLO'],
      speed: 60,
      direction: 'left',
      gap: 80,
      color: '#9aa4b2',
      fontSize: 64,
      fontWeight: 600,
      height: 120,
    },
  },
  {
    name: 'MaskReveal',
    frame: 14,
    props: {
      text: 'Onda',
      direction: 'left',
      color: '#f2f2f4',
      fontSize: 120,
      fontWeight: 600,
      duration: 24,
    },
  },
  {
    name: 'MatrixDecode',
    frame: 26,
    props: {
      text: 'DECODE',
      fontSize: 140,
      scrambleColor: '#d96b82',
      color: '#f2f2f4',
      fontWeight: 700,
      scrambleDuration: 24,
      charDelay: 4,
      scrambleSpeed: 2,
      seed: 7,
      align: 'center',
    },
  },
  {
    name: 'MeshGradient',
    frame: 90,
    props: {
      colors: ['#d96b82', '#7b9ed9', '#e8c06b'],
      background: '#08080a',
      speed: 1.2,
      seed: 7,
      opacity: 0.7,
    },
  },
  {
    name: 'NodeGraph',
    frame: 60,
    props: {
      hubLabel: 'AI',
      accent: '#d96b82',
      glow: true,
      background: '#08080a',
      centerX: 0.5,
      centerY: 0.5,
    },
  },
  {
    name: 'Parallax',
    frame: 120,
    props: {
      layers: [
        {
          src: 'DEMO_IMAGE',
          speed: 0.4,
          scale: 1.08,
          opacity: 0.55,
        },
        {
          src: 'DEMO_IMAGE',
          speed: 1,
          scale: 1.05,
        },
      ],
      direction: 'left',
      distance: 80,
      duration: 180,
      delay: 0,
    },
  },
  {
    name: 'PieReveal',
    frame: 52,
    props: {
      data: [
        {
          value: 48,
          color: '#d96b82',
          label: 'Onda',
        },
        {
          value: 27,
          color: '#5b8def',
          label: 'Remotion',
        },
        {
          value: 15,
          color: '#f2c14e',
          label: 'Lottie',
        },
        {
          value: 10,
          color: '#3a3a44',
          label: 'Other',
        },
      ],
      radius: 200,
      innerRadius: 110,
      holeColor: '#0a0a0f',
      showLabel: true,
      label: '4',
      labelColor: '#f2f2f4',
      fontSize: 80,
      duration: 24,
      stagger: 5,
    },
  },
  {
    name: 'PricingCard',
    frame: 48,
    props: {
      tier: 'Pro',
      price: '$29',
      period: '/month',
      features: [
        'Unlimited renders',
        'Signature motion identity',
        'Source you own, copied in',
        'Priority support',
      ],
      cta: 'Get started',
      recommended: true,
      accent: '#d96b82',
      priceSize: 64,
      width: 380,
    },
  },
  {
    name: 'ProgressBar',
    frame: 30,
    props: {
      value: 72,
      width: 720,
      height: 16,
      accentColor: '#d96b82',
      trackColor: '#26262e',
      color: '#f2f2f4',
      fontSize: 32,
      showValue: true,
    },
  },
  {
    name: 'ProgressSteps',
    frame: 36,
    props: {
      steps: ['Plan', 'Build', 'Render', 'Ship'],
      current: 2,
      width: 900,
      accentColor: '#d96b82',
      dimColor: '#26262e',
      labelColor: '#8e8e98',
      fontSize: 34,
      dotSize: 30,
    },
  },
  {
    name: 'PulsingIndicator',
    frame: 15,
    props: {
      color: '#d96b82',
      size: 40,
      label: 'LIVE',
      labelColor: '#8e8e98',
      fontSize: 48,
      period: 45,
      x: 760,
      y: 500,
    },
  },
  {
    name: 'QuoteCard',
    frame: 95,
    props: {
      quote: 'Design is intelligence made visible.',
      author: 'Alina Wheeler',
      role: 'Brand Designer',
      accent: true,
      quoteFontSize: 56,
      authorFontSize: 24,
      delay: 0,
    },
  },
  {
    name: 'RgbGlitch',
    frame: 50,
    props: {
      text: 'SIGNAL',
      fontSize: 160,
      intensity: 14,
      baseSplit: 3,
    },
  },
  {
    name: 'RotateIn',
    frame: 8,
    props: {
      fromDegrees: -8,
      delay: 0,
      durationInFrames: 18,
    },
  },
  {
    name: 'ShimmerSweep',
    frame: 18,
    props: {
      text: 'Shipping today',
      shimmerColor: '#f2f2f4',
      color: '#8e8e98',
      fontSize: 120,
      fontWeight: 600,
      duration: 36,
      x: 320,
      y: 300,
    },
  },
  {
    name: 'SkeletonCard',
    frame: 38,
    props: {
      lines: 4,
      thumbnail: true,
      shimmerSpeed: 48,
      width: 520,
      barHeight: 20,
    },
  },
  {
    name: 'SlotMachineRoll',
    frame: 30,
    props: {
      text: '2026',
      fontSize: 180,
      fontWeight: 700,
      color: '#f2f2f4',
      reelLength: 14,
      charDelay: 5,
      seed: 7,
    },
  },
  {
    name: 'SplitScreen',
    frame: 10,
    props: {
      orientation: 'horizontal',
      ratio: 0.5,
      gap: 2,
      divider: true,
      animate: true,
      delay: 0,
      width: 1120,
      height: 600,
    },
  },
  {
    name: 'Spotlight',
    frame: 24,
    props: {
      x: 0.5,
      y: 0.45,
      radius: 45,
      delay: 0,
      durationInFrames: 24,
      color: '#ffe9b0',
      softness: 65,
    },
  },
  {
    name: 'SpotlightCard',
    frame: 42,
    props: {
      eyebrow: 'FEATURE',
      title: 'Motion identity',
      body: 'One consistent feel across every component.',
      glowColor: '#d96b82',
      width: 560,
      padding: 48,
      align: 'left',
    },
  },
  {
    name: 'StaggerGroup',
    frame: 36,
    props: {
      items: ['Less is more', 'Calm is power', 'Motion has a feel', 'Made to be edited'],
      direction: 'column',
      align: 'center',
      gap: 24,
      stagger: 6,
      duration: 18,
      fontSize: 72,
      fontWeight: 600,
      color: '#f2f2f4',
    },
  },
  {
    name: 'Terminal',
    frame: 58,
    props: {
      command: 'npx ondajs add code-block',
      output: ['✓ added code-block', '✓ wrote 4 files', '✓ done in 1.2s'],
      prompt: '$',
      title: 'zsh — onda',
      typeSpeed: 30,
      fontSize: 44,
      width: 920,
    },
  },
  {
    name: 'TextFadeReplace',
    frame: 46,
    props: {
      from: 'ship',
      to: 'render',
      delay: 30,
      durationInFrames: 18,
      fontSize: 120,
      color: '#F2F2F4',
      fontWeight: 600,
    },
  },
  {
    name: 'Timeline',
    frame: 70,
    props: {
      events: [
        {
          label: 'Concept',
        },
        {
          label: 'Build',
        },
        {
          label: 'Ship',
        },
        {
          label: 'Iterate',
        },
      ],
      spacing: 130,
      dotSize: 20,
      fontSize: 30,
      lineColor: '#26262e',
      dotColor: '#f2f2f4',
      accentColor: '#d96b82',
      labelColor: '#9aa4b2',
    },
  },
  {
    name: 'TrackingIn',
    frame: 14,
    props: {
      text: 'ONDA',
      fontSize: 140,
      fontWeight: 600,
      color: '#f2f2f4',
      fromTracking: 0.55,
      tracking: -0.02,
      blur: true,
      align: 'center',
    },
  },
  {
    name: 'Typewriter',
    frame: 14,
    props: {
      text: 'motion graphics',
      durationInFrames: 24,
      cursor: true,
      cursorColor: '#d96b82',
      color: '#f2f2f4',
      fontSize: 80,
      fontWeight: 500,
    },
  },
  {
    name: 'Underline',
    frame: 60,
    props: {
      text: 'motion graphics',
      fontSize: 96,
      color: '#f2f2f4',
      accentColor: '#d96b82',
      lineThickness: 4,
      lineOffset: 10,
      delay: 0,
      duration: 18,
      lineDelay: 8,
      lineDuration: 10,
    },
  },
  {
    name: 'VideoClip',
    frame: 12,
    props: {
      src: 'DEMO_IMAGE',
      fadeIn: 18,
      fadeOut: 18,
      durationInFrames: 90,
      fit: 'cover',
      letterbox: 60,
      borderRadius: 12,
    },
  },
  {
    name: 'Vignette',
    frame: 0,
    props: {
      intensity: 0.7,
      innerRadius: 35,
      color: '#000000',
    },
  },
  {
    name: 'WordRotate',
    frame: 78,
    props: {
      phrases: ['fast', 'beautiful', 'restrained'],
      align: 'center',
      fontSize: 120,
      fontWeight: 600,
      color: '#f2f2f4',
      holdDuration: 30,
      transitionDuration: 12,
    },
  },
  {
    name: 'WordStagger',
    frame: 28,
    props: {
      text: 'motion that moves you',
      fontSize: 96,
      color: '#f2f2f4',
      width: 1080,
      fontWeight: 600,
      justify: 'center',
      stagger: 4,
    },
  },
]

const registry = Lib as Record<string, unknown>
const sample = () => h(Text, { fontSize: 80, color: '#ffffff', fontWeight: 700 }, 'Onda')

describe('ported components render without throwing', () => {
  for (const c of CASES) {
    it(`${c.name} @ frame ${c.frame}`, () => {
      const Comp = registry[c.name] as FunctionComponent<Record<string, unknown>> | undefined
      expect(typeof Comp).toBe('function')
      const el = h(
        Composition,
        { width: 1280, height: 720, fps: 30, durationInFrames: 120 },
        h(Comp as FunctionComponent<Record<string, unknown>>, c.props, sample()),
      )
      const scene: Scene = renderFrame(el, c.frame)
      expect((scene.root.children ?? []).length).toBeGreaterThan(0)
    })
  }
})
