//! In-browser image resolution.
//!
//! The wasm engine decodes `data:` URIs but can't fetch URL/path image sources
//! (there's no filesystem or fetch inside the render call). So the Player resolves
//! image `src` URLs to `data:` URIs in JS — the browser fetches + the engine's
//! existing `data:` decode path handles them. Resolved URIs are cached and shared
//! across players, so each image is fetched once.

// Resolved `url -> data: URI`. Module-level so multiple <Player>s share it.
const cache = new Map<string, string>()
const inflight = new Map<string, Promise<void>>()
// URLs whose fetch finished UNsuccessfully (404 / CORS / network). Tracked so the
// on-demand resolver treats them as "settled" and never re-fetches in a loop — a
// failed image just stays blank (same as before), it doesn't peg the engine.
const failed = new Set<string>()

/** Fetch `url` and convert it to a `data:` URI, caching the result. Failures are
 *  recorded (not retried) — the image stays unresolved and the renderer skips it. */
export function resolveImageUrl(url: string): Promise<void> {
  if (cache.has(url) || failed.has(url) || typeof fetch === 'undefined') return Promise.resolve()
  const existing = inflight.get(url)
  if (existing) return existing
  const p = (async () => {
    try {
      const res = await fetch(url)
      if (!res.ok) {
        failed.add(url)
        return
      }
      const blob = await res.blob()
      const dataUri = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader()
        reader.onload = () => resolve(String(reader.result))
        reader.onerror = () => reject(reader.error)
        reader.readAsDataURL(blob)
      })
      cache.set(url, dataUri)
    } catch {
      // Network/CORS error — mark settled so we don't re-fetch it every repaint.
      failed.add(url)
    } finally {
      inflight.delete(url)
    }
  })()
  inflight.set(url, p)
  return p
}

/** True once `url` is decoded-ready: a `data:`/generated src needs no fetch, and a
 *  resolved URL is in the cache. Lets the render loop skip already-handled images
 *  and only kick off fetches for genuinely new ones (no repaint loop). */
export function imageResolved(url: string): boolean {
  return (
    url.startsWith('data:') || url.startsWith('onda-noise:') || cache.has(url) || failed.has(url)
  )
}

/** The minimal scene-node shape these walkers touch (a subset of `Scene`). */
interface ImageNode {
  kind?: { type?: string; src?: string }
  children?: ImageNode[]
}

/** Collect every non-`data:` image `src` URL in a scene tree. */
export function collectImageUrls(node: ImageNode | undefined, out: Set<string>): void {
  if (!node) return
  const src = node.kind?.type === 'image' ? node.kind.src : undefined
  // `data:` is already pixels; `onda-noise:` is generated by the engine's image
  // pass — neither needs fetching to a data: URI.
  if (
    typeof src === 'string' &&
    src.length > 0 &&
    !src.startsWith('data:') &&
    !src.startsWith('onda-noise:')
  ) {
    out.add(src)
  }
  for (const child of node.children ?? []) collectImageUrls(child, out)
}

/** Rewrite each resolved image `src` URL to its cached `data:` URI, in place. */
export function applyResolvedImages(node: ImageNode | undefined): void {
  if (!node) return
  if (node.kind?.type === 'image' && typeof node.kind.src === 'string') {
    const dataUri = cache.get(node.kind.src)
    if (dataUri) node.kind.src = dataUri
  }
  for (const child of node.children ?? []) applyResolvedImages(child)
}
